### ISSUE TITLE
Practica #4 Diseño de base de datos relacional

### ISSUE THREAD

**Issue by antoniio** [SistemasTecTlaxiaco/diseno-de-bases-de-datos-relacional-mitte#2]
[Diagrama Relacional.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-bases-de-datos-relacional-mitte/files/6353289/Diagrama.Relacional.pdf)

**Comment by Nancy2050** [comment]
Bien, contiene todos los elementos descritos en la rúbrica.
Puntaje: 20%

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado...
